#服务通用配置
[server]
#服务名
appName="GoIn2.0"
#服务端口
port=8080
#token加密令牌
token="sdfhaoisnfy^&%^%$diffxzq9354djsa123^&^(nd_+##"
#数据加密
aesKey="IYuTTFVodna8JiUJCrP5Xe5REC#3GA1P"
#是否开启debug模式
debug=0

#权限配置
[casbin]
superRole="superman"
adminRole="admin"
basicRole="basic"

#文档权限控制
[docAuth]
admin="123456"

#MySQL数据库
[mysql]
dsn=""

#Redis数据库
[redis]
addr=""
db=0
password=""